name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  FORCE_COLOR: true

jobs:
  rust:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Wasm Build
      run: wasm-pack build
    - name: Generate JS constants
      run: cargo run --bin gen_constants
    - name: Install JS dependencies
      run: |
        cd web
        npm ci
    - name: Build JS
      run: |
        cd web
        npm run build
    - name: Wasm Test
      run: wasm-pack test --node
    - name: Rust Test
      run: cargo test
    - name: JS Test
      run: |
        cd web
        npm run test
    - name: Rust Lint
      run: |
        rustup component add clippy || exit 0
        cargo clippy
    - name: JS Lint
      run: |
        cd web
        npm run lint
