name: CI

on:
  push:
  schedule:
    - cron:  '30 18 * * 1'

env:
  CARGO_TERM_COLOR: always
  FORCE_COLOR: true

jobs:
  rust-build:
    name: Wasm build and JS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Wasm build
      run: |
        cd src/core
        wasm-pack build

  rust-test:
    name: Rust test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Wasm test
      run: |
        cd src/core
        wasm-pack test --node
    - name: Rust test
      uses: actions-rs/cargo@v1
      with:
        command: test

  rust-lint:
    name: Rust lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install with clippy
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: clippy
    - name: clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy

  rust-audit:
    name: Rust audit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Audit
      uses: actions-rs/cargo@v1
      with:
        command: audit
